{% set name = "qibojit" %}
{% set version = "0.1.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/qiboteam/qibojit/archive/v{{ version }}.tar.gz
  sha256: 17849db49d51ccadf12e4606da08ce94f24924074bf0dc2c9fc87863025a906c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9,<3.12
    - poetry
  run:
    - numba >=0.51.0
    - scipy
    - psutil
    - python >=3.9,<3.12
    - qibo >=0.2.5

test:
  imports:
    - qibojit

about:
  home: https://github.com/qiboteam/qibojit
  summary: Simulation tools based on numba and cupy for Qibo.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - scarrazza
